### ISSUE TITLE
Unable to start the Program

### ISSUE THREAD

**Issue by Powerbock** [fnzeta/Camsoda-Recorder#4]
I have this very helpful program running for a very long time, but now only a error at starting.

checking for online models
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    if should_record_model(conf.settings).check(model):
  File "/home/ronald/Camsoda-Recorder/classes/camsoda.py", line 201, in check
    if model['tpl'][1] in Wanted(self._settings).wanted_models:
KeyError: 1

Camsoda any Change on her Website? 
Any Chance for Help?
Kind Regards
Powerbock

Windows 10 with Python3 
Ubuntu 20 with Python3

**Comment by bobert1235** [comment]
any updates?
